### ISSUE TITLE
Updating the circle config

### ISSUE THREAD

**Issue by alkymst** [drud/ddev-ui#101]
## What happened (or feature request):

1. Updating the circle config to to use `jobs` instead of `stages`
2. Nightly builds

## What you expected to happen:
Remove this error and establish nightly builds.
<img width="523" alt="screenshot 2018-06-28 14 20 05" src="https://user-images.githubusercontent.com/192756/42059106-a2b1676e-7adf-11e8-85fd-5089bce0ff32.png">

## How to reproduce this:
Trigger a deploy in circleci.

## Anything else do we need to know:

- [x] Break things into distinct workflows vs 1 single process.
- [x] Setup Test Triggers
- [x]  Github artifact building of releases.

## Related source links or issues:
https://circleci.com/docs/2.0/sample-config/
https://circleci.com/docs/2.0/testing-ios/
https://circleci.com/docs/2.0/configuration-reference/

**Comment by dclear** [comment]
@alkymst to flesh this out a bit more.

Look into integrating https://www.npmjs.com/package/license-compatibility-checker or similar

**Comment by dclear** [comment]
done in v0.6; closing
