### ISSUE TITLE
Review Licensing

### ISSUE THREAD

**Issue by alkymst** [drud/ddev-ui#103]
There are two overarching options here:
1. Keep as separate repos (not the current plan) and therefore we have license flexibility or.
2. Merge the repos (the current desire/plan) and that would mean we are Apache 2.

We basically need to make sure our tech stack is Apache 2 compliant. If it is, this is trivial. Time spent will be in making that determination.

**Comment by cyberswat** [comment]
It looks like we are good on this issue based on the output above.
