### ISSUE TITLE
Convert DDEV-UI Repo from Private to Public

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev-ui#106]
Once we officially release DDEV-UI, we will likely want/need to open up our repository so that bugs and feature requests are filed against it instead of the drud/ddev repo. To do this, we need to address [the standards we set forth in our community documentation](https://github.com/drud/community/blob/d50141aebe2fca03ad5f3e381586dbaa54c6785c/development/publishing_repositories.md).

* [x] The project has an appropriate and meaningful name.
* [x] The project has a brief, meaningful description.
* [x] The project has a README.md committed in the root of repo. The README clearly describes the project and its benefits to users.
* [x] The README has any applicable badges added for the project to indicate build status, maintenance status, etc.
* [x] The project has [our issue and pull request templates](https://github.com/drud/general/tree/master/.github) if we will be accepting issues and pull requests from outside contributors.
* [x] The project has a LICENSE committed in the root of repo. The Apache 2.0 License should be used for all DRUD projects. If a different license is more appropriate or required for a project, create a ticket in drud/general to discuss the circumstances for that project.
* [x] If possible, Circleci tests should be configured, enabled, useful, and passing. Circle config would normally involve configuration of building on forked repos as well.
* [x] The project should have no work-in-progress feature branches, and the immediate commit history should provide appropriate, meaningful commit messages.
* [x] Ideally, the project provides at least one tagged release.
* [ ] Ideally, the project provides some level of test coverage.

Tagging w/v0.5.0 because it's unlikely we will get to this before the next release window.

**Comment by cyberswat** [comment]
This repo has been converted to public.
