### ISSUE TITLE
Start, Stop, and Restart

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev-ui#13]
## What happened (or feature request):

Feature Request

## What you expected to happen:

* On an app overview page, users can see the current site status (e.g. stopped or running).
* On an app overview page, if the status is "stopped", a user can click a button to trigger a start.
* On an app overview page, if the status is "running", a user can click a button to trigger a stop.
* On an app overview page, if the status is "running", a user can click a button to trigger a restart.
* A success or failure message is displayed to the user at the end of each action.
* The status updates based on the result of each action.

**Comment by dclear** [comment]
Re-opening for us to review in backlog.

**Comment by dclear** [comment]
wrong issue; re-closing
