### ISSUE TITLE
State management on project setup: disable steps ahead of current

### ISSUE THREAD

**Issue by btopro** [drud/ddev-ui#134]
## What happened (or feature request):
I clicked on the container settings number before being at that step

## What you expected to happen:
It wouldn't allow me to do so (QA'ing here)

## How to reproduce this:
Click to start a new project, then on the initial screen click Continer settings or Platform setup
![2018-09-06_09-56-48](https://user-images.githubusercontent.com/329735/45162153-5356d380-b1bb-11e8-8efb-2b5fafcd3e34.png)

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.
v0.4.1-alpha

## Anything else do we need to know:
It seems to lose state as it goes back to the 1st screen being the project overview page when clicking one of those
![2018-09-06_09-56-35](https://user-images.githubusercontent.com/329735/45162210-72556580-b1bb-11e8-8fe5-ff5fe324eac4.png)

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)
1, should just be ensuring that those buttons can't be clicked prior to being on those steps or that they aren't clickable at all and just indicate the step you're currently on

**Comment by dclear** [comment]
Thanks for the feedback, @btopro. We'll bring this issue into our backlog.

**Comment by alkymst** [comment]
This is resolved in #154. It will be in the next release on Wednesday. Thanks for pointing it out @btopro!
