### ISSUE TITLE
Add Tooltip / Helper Text to Icons

### ISSUE THREAD

**Issue by dclear** [drud/ddev-ui#136]
## What happened (or feature request):

Add tooltip / helper text to identify icons on mouseover

![tool-tip](https://user-images.githubusercontent.com/1197912/45248607-55f71d00-b2d0-11e8-9176-a64d186d7cd7.png)

**Comment by alkymst** [comment]
This is resolved with this PR - #157

**Comment by alkymst** [comment]
PR #157 was merged.
