### ISSUE TITLE
Error Handling When Docker stops running during active DDEV UI session

### ISSUE THREAD

**Issue by dclear** [drud/ddev-ui#141]
## What happened (or feature request):

Stub: When docker shuts down / quits while app is running, we get a blank screen in DDEV UI without user prompt.

## What you expected to happen:

- [x] Add Error catching outside of react.
- [x] Need to show error to user. 
- [x] "Could not connect to docker.." warning should go away when Docker is running again.

**Comment by rfay** [comment]
I do think it would be better to rely on ddev rather than also relying on docker. ddev checks for docker. If we need to improve ddev's ability to report we can.

**Comment by dclear** [comment]
I stubbed out an issue for that at https://github.com/drud/ddev-ui/issues/142

**Comment by alkymst** [comment]
Have a WIP PR here - https://github.com/drud/ddev-ui/pull/144/

**Comment by alkymst** [comment]
This should be ready to go.
