### ISSUE TITLE
Fix `[object Object]` over icon text in siteList

### ISSUE THREAD

**Issue by dclear** [drud/ddev-ui#143]
## What happened (or feature request):

Fix `[object Object]` over icon text in siteList

## How to reproduce this:

Mouseover on a site icon in the site listing

<img width="601" alt="screen shot 2018-09-14 at 2 20 34 pm" src="https://user-images.githubusercontent.com/1197912/45573291-660b8100-b829-11e8-837f-5f8272040f51.png">

**Comment by alkymst** [comment]
PR #155 was merged
