### ISSUE TITLE
Standardize on app terminology: Project

### ISSUE THREAD

**Issue by dclear** [drud/ddev-ui#145]
## What happened (or feature request):

- [x] Standardize on app terminology
- [x] MVP: Replace "Install" in buttons with "Project".
- [x] Stretch: Cleanup extraneous verbiage

## How to reproduce this:

![screen shot 2018-09-14 at 2 22 45 pm](https://user-images.githubusercontent.com/1197912/45573652-825bed80-b82a-11e8-8602-5f56d059c418.png)

![marked-up-project](https://user-images.githubusercontent.com/1197912/45573930-61e06300-b82b-11e8-8b68-e97095fbcfe0.png)

**Comment by alkymst** [comment]
PR here - #156

**Comment by alkymst** [comment]
PR #156 has been merged.
