### ISSUE TITLE
Rename/rebrand ddev-ui to avoid confusion for hosting UI users

### ISSUE THREAD

**Issue by rfay** [drud/ddev-ui#160]
## What happened (or feature request):

I'm pretty sure we're branding hosting as DDEV-Live, which means that having ddev-ui, which is a UI on DDEV-Local as "ddev-ui" is going to be very, very painful as the UI on *hosting* comes out.

We really, really need to be proactive with this naming problem before it causes confusion for our lovely customers.

**Comment by alkymst** [comment]
Well it never really landed.

However I feel we can do a developers view into hosting through the DDEV-UI (DDEV-Desktop) but feel we will also need a web based hosting interface that doesn't require a download. Now it being built in React, if we do the web hosting UI in React we can start looking at reusing relevant UI components. However I know that some of the team didn't like the idea of tying the 2 into one thing.

**Comment by rfay** [comment]
I personally think that trying to mix a dev tool (ddev-ui) with a hosting admin interface would be a really confusing and arbitrary thing. Like Pantheon admin UI doesn't try to be a dev tool.

**Comment by alkymst** [comment]
It allows for a workflow that has not been done before is my argument. Syncing environments, push button deploys, etc.

**Comment by cyberswat** [comment]
Are there useful parts of the hosting experience that would make sense to bundle into the ddev ui?  I could see some of the more complex functionallity being reserved for a website.  What about very simple functionallity like viewing logs in a way that would work both locally and remote?  That's one top of mind example.

I do believe that we would likely still need a larger interface for the deeper functions of hosting, but am wondering if there some type of an approach where it makes sense to at least partially combine the interfaces?  Admittedly, we don't even have a list of what functionallity we are talking about so this is still a little hypothetical.

**Comment by alkymst** [comment]
However, I think for sake of argument that **DDEV Desktop** is a better name.

**Comment by rfay** [comment]
"UI" is just bad everywhere. 

Not sure that "DDEV Desktop" would solve the confusion problem. However, if the actual hosting management UI is just called "DDEV-Live" itself it might work out. Pantheon's management interface is called "Pantheon Dashboard", which is easy. 

I just don't want people to be confused about what item is for what purpose. If the hosting management UI is entirely web-based, that would probably solve a lot of my concern, but it should still be named to imply its usage.

**Comment by dclear** [comment]
Let's continue this convo via proper internal channels. Closing here.
