### ISSUE TITLE
1-UI-Q4-18: Define user interface to support integration with DDEV Live						

### ISSUE THREAD

**Issue by dclear** [drud/ddev-ui#171]
## Objective Description

Define user interface to support integration with DDEV Live	

## Team
DDEV-UI

**Comment by cyberswat** [comment]
@dclear can we de-prioritize this issue and push everything related to it until after the API is available?

**Comment by dclear** [comment]
done: added incubate here and updated the spreadsheet with "deprioritize"

**Comment by dclear** [comment]
closing 2018 OKR epic container.
