### ISSUE TITLE
Flesh out user scenarios for test plan use - pt 1

### ISSUE THREAD

**Issue by mafriend** [drud/ddev-ui#185]
Goals: Each sprint, identify a small number of test scenarios from Product Feature Testing Outline to flesh out with full steps and release showstopper status

For this next sprint, let's try to flush out the following scenarios:
Scenario: I can create a blank WordPress project
Scenario: I can create a blank Drupal 6, 7 or 8 project
Scenario: I can start a connected DDEV project
Scenario: I can stop a connected DDEV project
Scenario: I can restart a connected DDEV project

These may seem like a lot of scenarios to attempt to tackle in one sprint, but the first two scenarios are  (hopefully going to be very similar) and once we flush out the details for one, the other should fall into place! 

Thanks!

**Comment by dclear** [comment]
@mafriend : flesh these out in this doc, correct?

https://docs.google.com/document/d/1RbY_3_pDOP-69oEcfeXcfqa9qwI2BPW13avFUw5YirM/edit#heading=h.4woucdstrfw9

**Comment by mafriend** [comment]
Yep! Sorry just saw this comment! but that is accurate!
