### ISSUE TITLE
Not able to move ddev-ui window around the screen

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev-ui#202]
## What happened (or feature request):
It is not possible to move the ddev-ui window around the screen.

## What you expected to happen:
It's expected that there would be a point on the window that the pointer can grab the window and move it around the screen.

## How to reproduce this:
Open ddev-ui, try to grab part of the window to move it.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.
Latest release for macOS - 0.6.0.531.

**Comment by damienmckenna** [comment]
I worked out the problem - you have to hover at the very edge of the window, once the resize pointer shows up you can grab the window and drag it around.

**Comment by alkymst** [comment]
@damienmckenna We have a small updated version that we have yet to cut the release for with some package updates and a larger draggable area defined in the app. We will try and get it scheduled to get an updated release out.

Thanks for the feedback!
