### ISSUE TITLE
Implement macOS signing cert

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev-ui#61]
## What happened (or feature request):

STUB. Related to #33 and #34

**Comment by dclear** [comment]
@cyberswat : in chatting with Nathan sounds like this one is blocked by account / creds / access and we need your assist.  I know we're in a holding pattern but tossing over to you for when we pick it back up.

**Comment by dclear** [comment]
status: we can code sign for Mac Store release but not releasing outside of the app store

**Comment by cyberswat** [comment]
Closing as this does not align with current goals.
